name: CI zkvm-sp1

defaults:
  run:
    working-directory: ./zkvm/sp1

on:
  pull_request:
    paths:
      - 'hash-sig/**'
      - 'zkvm/sp1/**'
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install toolchain for SP1
        run: |
          curl -L https://sp1up.succinct.xyz | bash
          $HOME/.sp1/bin/sp1up

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Run instantiation sha3
        run: cargo run --release --bin hash-sig-agg-zkvm-sp1-script -- -i sha3 --size 1 --debug

      - name: Run instantiation poseidon2-baby-bear
        run: cargo run --release --bin hash-sig-agg-zkvm-sp1-script -- -i poseidon2-baby-bear --size 1 --debug

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rust-docs, rustfmt, clippy

      - name: Install toolchain for SP1
        run: |
          curl -L https://sp1up.succinct.xyz | bash
          $HOME/.sp1/bin/sp1up

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Run fmt
        run: cargo fmt --all -- --check

      - name: Run check
        run: cargo check

      - name: Run clippy
        run: cargo clippy --all-features --all-targets
